blog/urls.py
from django.urls import path, include
from .views import PublicarListView,PublicarDetailView,PublicarCreateView,PublicarDeleteView,ModificarPublicacionUpdateView,CategoryView,CategoryListView,AddCategoryView


urlpatterns = [
    path('publicar/', PublicarListView.as_view(), name='publicar'),
    path('publicacion_detalle/<int:pk>', PublicarDetailView.as_view(), name='publicacion_detalle'),
    path('agregar_publicacion', PublicarCreateView.as_view(), name='agregar_publicacion'),
    path('modificar_publicacion/<int:pk>', ModificarPublicacionUpdateView.as_view(), name='modificar_publicacion'),
    path('publicacion_detalle/<int:pk>/eliminar', PublicarDeleteView.as_view(), name='eliminar_publicacion'),
    path('categoria/<str:cats>/',CategoryView, name='categoria'),
    path('category-list/',CategoryListView, name='category-list'),
    path('agregar_categoria/', AddCategoryView.as_view(), name='agregar_categoria'),
]

empresas/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('precio_empresas/<int:id>', views.precio_empresas, name='precio_empresas'),
    path('sectores', views.sectores, name='sectores'),   
    path('sector/<int:id>', views.sector, name='sector'),
    path('empresas', views.empresas, name='empresas'),
    path('empresa/<int:id>', views.empresa, name='empresa'),
    path('chart/<int:id>', views.line_chart, name='line_chart'),
    path('chart3/<int:id>', views.line_chart, name='line_chart3'),
    path('chartJSON/<int:id>', views.line_chart_json2, name='line_chart_json'),
    path('chartJSON3/<int:id>', views.line_chart_json3, name='line_chart_json3'),
    path('registro/', views.registro, name='registro'),
    path('acceso/', views.acceso, name='acceso'),
    path('salida/', views.salidaUsuario, name='salida'),
    path('', views.index, name='index'),
]

sectorFinanciero/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from empresas import views

router = routers.DefaultRouter()
router.register(r'sector', views.SectorViewSet)
router.register(r'empresa', views.EmpresaViewSet)
router.register(r'precioempresa', views.PrecioempresaViewSet)
router.register(r'preciosector', views.PreciosectorViewSet)

urlpatterns = [
    path('', include(('empresas.urls','empresas'), namespace='empresas')),
    path('blog/', include('blog.urls')),
    path('registration/', include('django.contrib.auth.urls')),
    path('registration/', include('registration.urls')),
    path('admin/', admin.site.urls),
        # Rutas para la url /api/
    path('api/', include(router.urls)),
    path('api/auth/', include('rest_framework.urls',
        namespace="rest_framework")),

]

empresas/models.py
from django.db import models

# Create your models here.

class Sector(models.Model):
    nombre = models.CharField(max_length=50)
    ticker = models.CharField(max_length=20)

    def __str__(self):
        return f"{self.nombre}, {self.ticker}"

class Empresa(models.Model):
    nombre = models.CharField(max_length=50)
    pais = models.CharField(max_length=20)
    ticker = models.CharField(max_length=20, null= True, blank=True)
    id_sector = models.ForeignKey(Sector, on_delete=models.CASCADE)
    sector = models.CharField(max_length=50, null=True)
    industria = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=2000)

    def __str__(self):
        return f"{self.nombre}, {self.ticker}"

class PrecioEmpresa(models.Model):
    id_empresa = models.ForeignKey(Empresa,on_delete= models.CASCADE,related_name='emp')
    nombre_empresa = models.CharField(max_length=50)
    fecha = models.DateField()
    precio_apertura = models.FloatField()
    precio_maximo = models.FloatField()
    precio_minimo = models.FloatField()
    precio_cierre = models.FloatField()
    volumen = models.FloatField()

    def __str__(self):
        return f"{self.pk},{self.id_empresa}, {self.nombre_empresa}"

class PrecioSector(models.Model):
    id_sector = models.ForeignKey(Sector,on_delete= models.CASCADE)
    nombre_sector = models.CharField(max_length=50)
    fecha = models.DateField()
    precio_apertura = models.FloatField()
    precio_maximo = models.FloatField()
    precio_minimo = models.FloatField()
    precio_cierre = models.FloatField()
    volumen = models.FloatField()
    
    

empresas/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

empresas/views.py
from django.shortcuts import render,HttpResponse, get_object_or_404,redirect
from .models import Sector,PrecioEmpresa,Empresa, PrecioSector
from django.views.generic import TemplateView
from chartjs.views.lines import BaseLineChartView
from django.http import JsonResponse
from rest_framework import viewsets
from .serializers import SectorSerializer, EmpresaSerializer, PrecioempresaSerializer, PreciosectorSerializer
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .forms import CreateUserForm

# Create your views here.

@login_required(login_url='acceso/')
def index(request):
    Sectores = Sector.objects.all()
    context = {'Sectores': Sectores }
    return render (request,"empresas/index.html",context)

@login_required(login_url='acceso/')
def sectores(request):
    Sectores = Sector.objects.all()
    context = {'Sectores': Sectores }
    return render (request,"empresas/sectores.html",context)

@login_required(login_url='acceso/')
def sector(request,id):
    sector = get_object_or_404(Sector, pk=id)
    return render (request,"empresas/sector.html",{"sector":sector})

@login_required(login_url='acceso/')
def precio_empresas(request,id):
    precio_empresa = get_object_or_404(PrecioEmpresa, pk=id)
    return render (request,"empresas/precio_empresas.html",{"precio_empresa":precio_empresa})

@login_required(login_url='acceso/')
def empresas(request):
    queryset = request.GET.get("buscar")
    empresas = Empresa.objects.all()
    if queryset:
        empresas = Empresa.objects.filter(
            nombre__icontains=queryset
        )
    paginator = Paginator(empresas, 10)
    page = request.GET.get('page')


    try:
        empresas = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        empresas = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        empresas= paginator.page(paginator.num_pages)


    # precios_empresa = empresa.precioempresa_set.all()
    return render(request,"empresas/empresas.html",{"empresas":empresas})


@login_required(login_url='acceso/')
def empresa(request,id):
    empresa = Empresa.objects.get(pk=id)
    precios_empresa = empresa.emp.all()
    return render(request,"empresas/empresa.html",{"precios_empresa":precios_empresa,"empresa":empresa})

def registro(request):
    if request.user.is_authenticated:
        return redirect('index/')
    
    else: 
        form = CreateUserForm()

        if request.method == 'POST':
            form = CreateUserForm(request.POST)
            if form.is_valid():
                form.save()
                user = form.cleaned_data.get('username')
                messages.success(request, 'La cuenta se ha registrado' + user)

                return redirect('registro')

        context = {
            'form':form
        }
        return render(request,'empresas/registro.html',context)

def acceso(request):

    if request.user.is_authenticated:
        return redirect('/')

    else: 
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username,password=password)

            if user is not None:
                login(request,user)
                return redirect('/') 

            else:
                messages.info(request,'Username OR password is incorrect')
                
        return render(request,'empresas/acceso.html')

def salidaUsuario(request):
    logout(request)
    return render(request,'empresas/acceso.html')


class LineChartJSONView(BaseLineChartView):

    def get_labels(self):
        """Return 7 labels for the x-axis."""
        #return ("January", "February", "March", "April", "May", "June", "July")
        empresa = Empresa.objects.get(pk=3)
        precios_empresa = empresa.emp.all()

        fechas = []
        for precio_empresa in precios_empresa:
            fechas.append(precio_empresa.fecha)

        return fechas


    def get_providers(self):
        """Return names of datasets."""
        return ["Central"]

    def get_data(self):

        empresa = Empresa.objects.get(pk=3)
        precios_empresa = empresa.emp.all()

        precioCierre = []
        for precio_empresa in precios_empresa:
            precioCierre.append(precio_empresa.precio_cierre)


        return [precioCierre]

        #return [[75, 44, 92, 11, 44, 95, 35],
         #       [41, 92, 18, 3, 73, 87, 92],
          #      [87, 21, 94, 3, 90, 13, 65]]

line_chart = TemplateView.as_view(template_name='line_chart.html')
line_chart_json = LineChartJSONView.as_view()

def line_chart_json2(request,id):
    labels = []
    data = []

    #queryset = City.objects.values('country__name').annotate(country_population=Sum('population')).order_by('-country_population')

    empresa = Empresa.objects.get(pk=id)
    precios_empresa = empresa.emp.all()

    for precio_empresa in precios_empresa:
        labels.append(precio_empresa.fecha)
        data.append(precio_empresa.precio_cierre)

    return JsonResponse(data={
        'labels': labels,
        'datasets': [{'data':data,
        "backgroundColor": "rgba(202, 201, 197, 0.5)",
        "borderColor": "rgba(202, 201, 197, 1)",
        "pointBackgroundColor": "rgba(202, 201, 197, 1)",
        "pointBorderColor": "#fff",
        "label": "Central",
        "name": "Central"}],
    })

line_chart3 = TemplateView.as_view(template_name='line_chart3.html')
line_chart_json3 = LineChartJSONView.as_view()

def line_chart_json3(request,id):
    labels = []
    data = []

    #queryset = City.objects.values('country__name').annotate(country_population=Sum('population')).order_by('-country_population')

    empresa = Empresa.objects.get(pk=id)
    precios_empresa = empresa.emp.all()

    for precio_empresa in precios_empresa:
        labels.append(precio_empresa.fecha)
        data.append(precio_empresa.precio_cierre)

    return JsonResponse(data={
        'labels': labels,
        'datasets': [{'data':data,
        "backgroundColor": "rgba(202, 201, 197, 0.5)",
        "borderColor": "rgba(202, 201, 197, 1)",
        "pointBackgroundColor": "rgba(202, 201, 197, 1)",
        "pointBorderColor": "#fff",
        "label": "Central",
        "name": "Central"}],
    })



class SectorViewSet(viewsets.ModelViewSet):
    """
    API que permite realizar operaciones con la tabla sector
    """
    # Se define el conjunto de datos sobre el que va a operar la vita,
    # en este caso, sobre todos los usuarios disponibles.
    queryset = Sector.objects.all().order_by('id')

    # Se define el serializador encargado de transformar las peticiones
    # de json a objetos django y viceversa.
    serializer_class = SectorSerializer

class EmpresaViewSet(viewsets.ModelViewSet):
    """
    API que permite realizar operaciones con la tabla sector
    """
    # Se define el conjunto de datos sobre el que va a operar la vita,
    # en este caso, sobre todos los usuarios disponibles.
    queryset = Empresa.objects.all().order_by('id')

    # Se define el serializador encargado de transformar las peticiones
    # de json a objetos django y viceversa.
    serializer_class = EmpresaSerializer

class PrecioempresaViewSet(viewsets.ModelViewSet):
    """
    API que permite realizar operaciones con la tabla sector
    """
    # Se define el conjunto de datos sobre el que va a operar la vita,
    # en este caso, sobre todos los usuarios disponibles.
    queryset = PrecioEmpresa.objects.all()

    # Se define el serializador encargado de transformar las peticiones
    # de json a objetos django y viceversa.
    serializer_class = PrecioempresaSerializer

class PreciosectorViewSet(viewsets.ModelViewSet):
    """
    API que permite realizar operaciones con la tabla sector
    """
    # Se define el conjunto de datos sobre el que va a operar la vita,
    # en este caso, sobre todos los usuarios disponibles.
    queryset = PrecioSector.objects.all()

    # Se define el serializador encargado de transformar las peticiones
    # de json a objetos django y viceversa.
    serializer_class = PreciosectorSerializer

empresas/templates/empresas/acceso.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

                </div>
                
                {% for message in messages %}
                    <p id="messages">{{message}}</p>
                {% endfor %}
		
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'empresas:registro' %}" class="ml-2">Sign Up</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>

empresas/templates/empresas/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.10.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js"></script>
   <title> {% block titulo %}sectores financieros{% endblock titulo %}</title>
    
</head>
<body>
<!-- esta pagina contendra el narvar para las otras paginas  -->
<div >

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'empresas:index' %}">Inicio</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">


        <li class="nav-item active">
          <a class="nav-link" href="{% url 'empresas:sectores' %}">Sectores <span class="sr-only">(current)</span></a>
        </li>

        <li class="nav-item active">
          <a class="nav-link" href="{% url 'empresas:empresas' %}">Empresas<span class="sr-only">(current)</span></a>
        </li>

        <li class="nav-item active">
          <a class="nav-link" href="{% url 'agregar_publicacion' %}">Agregar Publicación <span class="sr-only">Karma</span></a>
        </li>
  
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'publicar' %}">Noticias  <span class="sr-only">Karma</span></a>
        </li>

        {% if cat_menu %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Categorías
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% for item in cat_menu %}
              <a class="dropdown-item" href="{% url 'categoria' item|slugify %}">{{ item }}</a>
            {% endfor %}
          </div>
        </li>

        {% else %}

        
      <li class="nav-item">
        <a class="nav-link" href="{% url 'category-list' %}">Categorías</a>
      </li>

      {% endif %}

        <li class="nav-item active">
          <a class="nav-link" href="{% url 'empresas:salida' %}">Salir  <span class="sr-only">(current)</span></a>
        </li>

        

      </ul>
    </div>
  </nav>
  




<!-- 
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'empresas:index' %}">Inicio</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'empresas:sectores' %}"> Sectores <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'empresas:empresas' %}"> Empresas </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Karma</a>
            </li>
            
          </ul>
        </div>
      </nav> -->



{% block header %}{% endblock header %}


</div>

<div class="container">
  {% block content %}{% endblock content %}
</div>

</body>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

</html>

empresas/templates/empresas/empresa.html
{% extends "empresas/base.html" %}
{% load static %}

    {% block titulo %}<title>{{empresa.nombre}}</title>{% endblock titulo %}

    {% block content %}

    
    <h1>{{empresa.nombre}}</h1>
    
    <div class="container">
        <canvas id="myChart"></canvas>
    </div>


   
    <table>
        <tr>
            <th>No</th>
            <th>Fecha</th>
            <th>Apertura</th>
            <th>Máximo</th>
            <th>Mínimo</th>
            <th>Cierre</th>
            <th>Volumen</th>
        </tr>
        {% for precio_empresa in precios_empresa %}
        <tr>
            <td>{{precio_empresa.id}}</td>
            <td>{{precio_empresa.fecha}}</td>
            <td>{{precio_empresa.precio_apertura}}</td>
            <td>{{precio_empresa.precio_maximo}}</td>
            <td>{{precio_empresa.precio_minimo}}</td>
            <td>{{precio_empresa.precio_cierre}}</td>
            <td>{{precio_empresa.volumen}}</td>
        </tr>
        {% endfor %}
    </table>
    

<!--
    <div class="p-2 bd-highlight " style=" width: 60%; margin-top: 10%;scroll-margin-right: 10%;margin-bottom: 10%;">
        <div class="d-flex bd-highlight ">
          <div class="p-2 bd-highlight "><canvas id="myChart" width=380px height="240px" ></canvas></div>
          <div class="p-2 bd-highlight"><img src="IPC.JPG" alt="" class="img-thumbnail"></div>
        </div>
-->
<div class="p-2 bd-highlight " style=" width: 60%; margin-top: 10%;scroll-margin-right: 10%;margin-bottom: 10%;">
    <div class="d-flex bd-highlight ">
        <div class="p-2 bd-highlight "></div>
            <script type="text/javascript">
                $.get('{% url "empresas:line_chart_json" empresa.id %}', function(data) {
                    var ctx = $("#myChart").get(0).getContext("2d");
                    new Chart(ctx, {
                        type: 'line', data: data, id: {{empresa.id}}
                        
                    });
                });
            </script>
        <div class="p-2 bd-highlight "></div>
        <script type="text/javascript">
            $.get('{% url "empresas:line_chart_json3" empresa.id %}', function(data) {
                var ctx = $("#myChart").get(0).getContext("2d");
                new Chart(ctx, {
                    type: 'line', data: data, id: {{empresa.id}}
                    
                });
            });
        </script>
        </div>
</div>
{% endblock content %}

empresas/templates/empresas/empresas.html
{% extends "empresas/base.html" %}
{% block header %}

    <h1>Listado de las empresas mas importantes de México </h1>

{% endblock header %}


{% block content %}

<div class="container">
    <div class="row">
      <div class="col-md-12 search">
        <form method="get">
          <div id="custom-search-input">
            <div class="input-group col-md-12">
              <input type="text" class="form-control" placeholder="Buscar..." name="buscar" value="{{request.GET.buscar}}" >
              <span class="input-group-list">
                <i class="icon icon-search"></i>
                <button type="submit" class="boton btn-success">Buscar</button>
              </span>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>

<ul>
    {% for empresa in empresas %}
        <li>
            <a href="{% url 'empresas:empresa' empresa.id %}">{{ empresa }}</a>
        </li>
    {% empty %}
        <li>no se han agregado empresas</li>
    {% endfor %}
</ul>


<div class="container h-100">
<div class="row justify-content-center h-100">
{% if empresas.has_next or empresas.has_previous %}

    <ul class="pagination">
        {% if empresas.has_previous %}
            <li><a href="?page={{ empresas.previous_page_number }}" class="btn btnpages"><i
                    class="glyphicon glyphicon-chevron-left"></i></a></li>
        {% endif %}
        {% for page in empresas.paginator.page_range %}
            <li class="{% if empresas.number == page %}active{% endif %}">
                <a class="btn btnpages" href="?page={{ page }}">{{ page }}</a></li>
        {% endfor %}

        {% if empresas.has_next %}
            <li>
                <a href="?page={{ empresas.next_page_number }}" class="btn btnpages">
                    <i class="glyphicon glyphicon-chevron-right"></i>
                </a>
            </li>
        {% endif %}
    </ul>



{% endif %}

</div>
<div>


{% endblock content %}

empresas/templates/empresas/index.html
{% extends "empresas/base.html" %}
{% block header %}

    <h1>Esta pagina sera la pagina inicial </h1>

{% endblock header %}


{% block content %}



<!--Contenedor principal-->
<div class="d-flex bd-highlight mb-3" >
  <div class="p-2 bd-highlight" style=" width: 30%; margin: 10%;">
      <ul class="navbar-nav">
       
        
          {% for sector in Sectores %}
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'empresas:sector' sector.id %}">{{ sector }} <span class="sr-only">(current)</span></a>
              
              </li>
          {% empty %}
              <li>no se han agregado sectores</li>
          {% endfor %}
     


          
        </ul>
  </div>
</div>
{% endblock content %}

empresas/templates/empresas/precio_empresas.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Precio Empresas</h1>
    <ul>
       
        <li>
            {{precio_empresa.id_empresa}}  {{precio_empresa.nombre_empresa}}  {{precio_empresa.fecha}} {{precio_empresa.precio_apertura}}{{precio_empresa.precio_maximo}}{{precio_empresa.precio_minimo}}{{precio_empresa.precio_cierre}}{{precio_empresa.volumen}}
        </li>

    </ul>
    </ul>
</body>
</html>

empresas/templates/empresas/sectores.html
{% extends "empresas/base.html" %}
{% block header %}

    <h1>Listado de las empresas mas importantes de México </h1>

{% endblock header %}


{% block content %}
<ul>
    {% for sector in Sectores %}
        <li>
            <a href="{% url 'empresas:sector' sector.id %}">{{ sector }}</a>
        </li>
    {% empty %}
        <li>no se han agregado sectores</li>
    {% endfor %}
</ul>



    <h2>
  esta pagina se podran  seleccionarlos distintos sectores 
  y los distintos sectores 
    </h2>
{% endblock content %}